name: clancy prod

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Docker Login on DockerHub
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }}

    - name: Docker Publish on DockerHub
      run: ./gradlew dockerPushDockerHub

    - name: Docker pull published image
      run: docker pull ${{ secrets.DOCKER_HUB_USER }}/clancy:2.0.0

      # Heroku API key
    - name: Docker Login on Heroku
      run: docker login --username=_ --password=${{ secrets.HEROKU_KEY }} registry.heroku.com

    - name: Docker tag on Heroku
      run: docker tag ${{ secrets.DOCKER_HUB_USER }}/clancy:2.0.0 registry.heroku.com/clancy-prod/worker

    - name: Docker push on Heroku
      run: docker push registry.heroku.com/clancy-prod/worker

      # An authentication template:
      # machine api.heroku.com
      #   login {user}
      #   password {api key}
    - name: Heroku auth file
      run: echo "${{ secrets.HEROKU_AUTH }}" > ~/.netrc

    - name: Heroku container login
      run: heroku container:login

    - name: Heroku container release
      run: heroku container:release worker -a clancy-prod
